// Auto-generated catalog data
import { Product } from "./types";

export const LOCAL_PRODUCTS: Product[] = [
  {
    "name": "BoAt Airdopes 141 True Wireless Earbuds",
    "slug": "boat-airdopes-141",
    "merchant": "BoAt",
    "merchant_campaign_id": 4232,
    "merchant_url": "https://www.boat-lifestyle.com/products/airdopes-141",
    "source_url": "https://www.boat-lifestyle.com/products/airdopes-141",
    "affiliate_url": "https://linksredirect.com/?cid=319615&subid=boat-airdopes-141&subid2=smartpick_product_page&source=api&url=https%3A%2F%2Fwww.boat-lifestyle.com%2Fproducts%2Fairdopes-141",
    "affiliate_short_url": "https://clnk.in/CBwt",
    "affiliate_provider": "cuelinks",
    "image_url": "https://www.boat-lifestyle.com/cdn/shop/files/AD141-FI_Black01_1024x.png?v=1698391770",
    "price": "1499",
    "old_price": "4490",
    "is_deal": true,
    "discount_percent": 67,
    "deal_badge": "67% OFF",
    "rating": 4.4,
    "review_count": 18450,
    "currency": "INR",
    "category": "Audio",
    "description": "The boAt Airdopes 141 delivers punchy signature bass through custom 8mm dynamic drivers, backed by an impressive 42-hour total playback battery. Equipped with ENx Environmental Noise Cancellation dual mics for crisp voice calls and BEAST Mode for ultra-low latency gaming.",
    "score": 91,
    "status": "active",
    "published": true,
    "specs": [
      "8mm dynamic drivers with boAt Signature Sound",
      "Up to 42 hours total playback (6 hrs earbuds + 36 hrs case)",
      "ASAP Fast Charge: 75 mins playtime from 5 mins charge",
      "Dual microphones with ENx Environmental Noise Cancellation",
      "BEAST Mode with 80ms low latency for gaming",
      "IPX4 sweat and splash water resistance",
      "Bluetooth v5.1 with Instant Wake N’ Pair (IWP) technology",
      "Type-C reversible charging interface"
    ]
  },
  {
    "name": "Noise Buds VS104 Truly Wireless Earbuds",
    "slug": "noise-buds-vs104",
    "merchant": "Noise",
    "source_url": "https://www.gonoise.com/products/noise-buds-vs104",
    "affiliate_url": "https://www.gonoise.com/products/noise-buds-vs104",
    "image_url": "https://www.boat-lifestyle.com/cdn/shop/files/AD141-FI_Grey01_1024x.png?v=1698391770",
    "price": "1299",
    "old_price": "3499",
    "is_deal": true,
    "discount_percent": 62,
    "deal_badge": "62% OFF",
    "rating": 4.1,
    "review_count": 11200,
    "currency": "INR",
    "category": "Audio",
    "description": "Compact wireless earbuds featuring 13mm drivers, 30 hours of playtime, and Instacharge technology for fast daily top-ups.",
    "score": 84,
    "status": "active",
    "published": true,
    "specs": [
      "13mm dynamic sound drivers",
      "Up to 30 hours total playtime",
      "Instacharge: 10 mins charge = 150 mins playtime",
      "Bluetooth v5.2 connectivity",
      "IPX5 water resistance rating"
    ]
  },
  {
    "name": "Keychron Q1 Pro Custom Mechanical Keyboard",
    "slug": "keychron-q1-pro-custom-mechanical-keyboard",
    "merchant": "Keychron",
    "source_url": "https://www.keychron.com/products/keychron-q1-pro-qmk-via-wireless-custom-mechanical-keyboard",
    "affiliate_url": "https://www.keychron.com/products/keychron-q1-pro-qmk-via-wireless-custom-mechanical-keyboard",
    "image_url": "/images/products/keychron-q1-pro.svg",
    "price": "$199.00",
    "old_price": "$219.00",
    "is_deal": true,
    "discount_percent": 9,
    "deal_badge": "9% OFF",
    "rating": 4.8,
    "review_count": 1420,
    "category": "Keyboards",
    "description": "The gold standard wireless mechanical keyboard for programmers. Full CNC machined aluminum body, hot-swappable switches, and open-source QMK/VIA keymap programming.",
    "score": 94,
    "status": "active",
    "specs": [
      "Full CNC Machined Aluminum Body",
      "QMK/VIA Open Source Programmability",
      "Bluetooth 5.1 & Wired Type-C",
      "Hot-Swappable K Pro Mechanical Switches",
      "Double-Gasket Mount Acoustics",
      "4000mAh Long-Life Battery"
    ]
  },
  {
    "name": "Logitech MX Mechanical Wireless Keyboard",
    "slug": "logitech-mx-mechanical-wireless-keyboard",
    "merchant": "Logitech",
    "source_url": "https://www.logitech.com/products/keyboards/mx-mechanical.html",
    "affiliate_url": "https://www.logitech.com/products/keyboards/mx-mechanical.html",
    "image_url": "/images/products/logitech-mx-mechanical.svg",
    "price": "$169.99",
    "old_price": "$169.99",
    "is_deal": false,
    "discount_percent": 0,
    "deal_badge": null,
    "rating": 4.6,
    "review_count": 2840,
    "category": "Keyboards",
    "description": "Low-profile mechanical keys tailored for speed and ergonomic wrist angles. Features proximity-sensing smart backlighting and seamless multi-device switching across Mac and Windows.",
    "score": 90,
    "status": "active",
    "specs": [
      "Low Profile Tactile Switches",
      "Smart Ambient Proximity Backlighting",
      "Multi-Device Easy-Switch (Pair 3 Devices)",
      "USB-C Rechargeable (up to 10 months without backlight)",
      "Logi Options+ Customizable Shortcuts"
    ]
  },
  {
    "name": "Logitech MX Master 3S Wireless Mouse",
    "slug": "logitech-mx-master-3s-wireless-mouse",
    "merchant": "Logitech",
    "source_url": "https://www.logitech.com/products/mice/mx-master-3s.html",
    "affiliate_url": "https://www.logitech.com/products/mice/mx-master-3s.html",
    "image_url": "/images/products/logitech-mx-master-3s.svg",
    "price": "$99.99",
    "old_price": "$99.99",
    "is_deal": false,
    "discount_percent": 0,
    "deal_badge": null,
    "rating": 4.8,
    "review_count": 9650,
    "category": "Mice",
    "description": "The definitive ergonomic performance mouse. MagSpeed electromagnetic scrolling flies through 1,000 code lines per second with near-silent clicks and tracking on glass.",
    "score": 96,
    "status": "active",
    "specs": [
      "8,000 DPI Darkfield Sensor (Tracks on Glass)",
      "MagSpeed Electromagnetic Scrolling",
      "90% Quieter Quiet-Click Switches",
      "Dedicated Thumb Wheel & Gesture Controls",
      "70-Day USB-C Battery Life"
    ]
  },
  {
    "name": "Logitech Lift Vertical Ergonomic Mouse",
    "slug": "logitech-lift-vertical-ergonomic-mouse",
    "merchant": "Logitech",
    "source_url": "https://www.logitech.com/products/mice/lift-vertical-ergonomic-mouse.html",
    "affiliate_url": "https://www.logitech.com/products/mice/lift-vertical-ergonomic-mouse.html",
    "image_url": "/images/products/logitech-lift-vertical.svg",
    "price": "$69.99",
    "old_price": "$69.99",
    "is_deal": false,
    "discount_percent": 0,
    "deal_badge": null,
    "rating": 4.5,
    "review_count": 3200,
    "category": "Mice",
    "description": "Designed specifically for small-to-medium hands. Places your forearm in an optimal 57-degree natural handshake angle, immediately relieving wrist tension during marathon dev sessions.",
    "score": 88,
    "status": "active",
    "specs": [
      "57-Degree Natural Handshake Ergonomic Angle",
      "SmartWheel Precision & Speed Scrolling",
      "Whisper-Quiet Left/Right Clicks",
      "Bluetooth Low Energy & Logi Bolt Receiver",
      "2-Year Battery Life (Single AA)"
    ]
  },
  {
    "name": "Dell UltraSharp 32 4K USB-C Hub Monitor (U3223QE)",
    "slug": "dell-ultrasharp-32-4k-monitor-u3223qe",
    "merchant": "Dell",
    "source_url": "https://www.dell.com/en-us/shop/dell-ultrasharp-32-4k-usb-c-hub-monitor-u3223qe/apd/210-bdph/monitors-monitor-accessories",
    "affiliate_url": "https://www.dell.com/en-us/shop/dell-ultrasharp-32-4k-usb-c-hub-monitor-u3223qe/apd/210-bdph/monitors-monitor-accessories",
    "image_url": "/images/products/dell-ultrasharp-32.svg",
    "price": "$719.99",
    "old_price": "$899.99",
    "is_deal": true,
    "discount_percent": 20,
    "deal_badge": "20% OFF",
    "rating": 4.7,
    "review_count": 1120,
    "category": "Monitors",
    "description": "Developer-grade 31.5-inch 4K monitor with breakthrough IPS Black technology delivering a 2,000:1 contrast ratio. Single cable 90W USB-C hub with built-in KVM and RJ45 ethernet.",
    "score": 93,
    "status": "active",
    "specs": [
      "31.5-inch 4K UHD (3840x2160) IPS Black Panel",
      "2000:1 Contrast Ratio with 98% DCI-P3 Color",
      "90W USB-C Power Delivery & RJ45 Ethernet",
      "Built-in KVM Switch & Picture-by-Picture",
      "Fully Articulating Height, Tilt, Swivel Stand"
    ]
  },
  {
    "name": "LG 34WN80C-B 34-Inch Curved UltraWide Monitor",
    "slug": "lg-34wn80c-b-34-inch-curved-ultrawide",
    "merchant": "LG",
    "source_url": "https://www.lg.com/us/monitors/lg-34wn80c-b-ultrawide-monitor",
    "affiliate_url": "https://www.lg.com/us/monitors/lg-34wn80c-b-ultrawide-monitor",
    "image_url": "/images/products/lg-34wn80c-ultrawide.svg",
    "price": "$469.99",
    "old_price": "$549.99",
    "is_deal": true,
    "discount_percent": 15,
    "deal_badge": "15% OFF",
    "rating": 4.5,
    "review_count": 4190,
    "category": "Monitors",
    "description": "Expansive 34-inch 21:9 curved workspace allowing 3 full code windows side-by-side without bezels. Includes USB-C connectivity with 60W charging.",
    "score": 89,
    "status": "active",
    "specs": [
      "34-inch QHD (3440x1440) 21:9 Curved IPS Display",
      "USB-C Single Cable with 60W Power Delivery",
      "HDR10 with 99% sRGB Color Accuracy",
      "OnScreen Screen Split 2.0 Window Snapping",
      "Ergonomic Height & Tilt Adjustable Base"
    ]
  },
  {
    "name": "Apple MacBook Pro 14\" (M3 Pro)",
    "slug": "apple-macbook-pro-14-m3-pro",
    "merchant": "Apple",
    "source_url": "https://www.apple.com/macbook-pro-14-and-16/",
    "affiliate_url": "https://www.apple.com/macbook-pro-14-and-16/",
    "image_url": "/images/products/macbook-pro-14-m3.svg",
    "price": "$1,799.00",
    "old_price": "$1,999.00",
    "is_deal": true,
    "discount_percent": 10,
    "deal_badge": "10% OFF",
    "rating": 4.9,
    "review_count": 2150,
    "category": "Laptops",
    "description": "The premier developer laptop with 11-core CPU, 14-core GPU, Liquid Retina XDR display, and unmatched battery longevity for compiling code on the go.",
    "score": 97,
    "status": "active",
    "specs": [
      "Apple M3 Pro Chip (11-Core CPU, 14-Core GPU)",
      "14.2-inch Liquid Retina XDR with 120Hz ProMotion",
      "18GB High-Bandwidth Unified Memory",
      "Up to 18 Hours Real-World Battery Life",
      "3x Thunderbolt 4 Ports, HDMI, SDXC, MagSafe 3"
    ]
  },
  {
    "name": "Dell XPS 15 9530 (Intel Core i7 OLED)",
    "slug": "dell-xps-15-9530-oled-laptop",
    "merchant": "Dell",
    "source_url": "https://www.dell.com/en-us/shop/dell-laptops/xps-15-laptop/spd/xps-15-9530-laptop",
    "affiliate_url": "https://www.dell.com/en-us/shop/dell-laptops/xps-15-laptop/spd/xps-15-9530-laptop",
    "image_url": "/images/products/dell-xps-15.svg",
    "price": "$1,499.00",
    "old_price": "$1,799.00",
    "is_deal": true,
    "discount_percent": 17,
    "deal_badge": "17% OFF",
    "rating": 4.4,
    "review_count": 1450,
    "category": "Laptops",
    "description": "The gold standard Windows laptop for software engineering and creative builds. Vivid 3.5K OLED touchscreen with carbon fiber deck and 13th Gen Intel power.",
    "score": 87,
    "status": "active",
    "specs": [
      "13th Gen Intel Core i7-13700H (14 Cores, 20 Threads)",
      "15.6-inch 3.5K (3456x2160) InfinityEdge OLED Touch",
      "16GB DDR5 4800MHz & 512GB PCIe 4.0 SSD",
      "NVIDIA GeForce RTX 4050 6GB GDDR6",
      "Precision Milled Aluminum & Carbon Fiber Palmrest"
    ]
  },
  {
    "name": "Herman Miller Aeron Ergonomic Office Chair",
    "slug": "herman-miller-aeron-ergonomic-chair",
    "merchant": "Herman Miller",
    "source_url": "https://store.hermanmiller.com/office-chairs/aeron-chair/2195368.html",
    "affiliate_url": "https://store.hermanmiller.com/office-chairs/aeron-chair/2195368.html",
    "image_url": "/images/products/herman-miller-aeron.svg",
    "price": "$1,270.00",
    "old_price": "$1,495.00",
    "is_deal": true,
    "discount_percent": 15,
    "deal_badge": "15% OFF",
    "rating": 4.9,
    "review_count": 5400,
    "category": "Desk Setup",
    "description": "The industry standard for ergonomic posture support. Breathable Pellicle 8Z elastomeric mesh balances pressure distribution across 8 distinct tension zones with PostureFit SL sacral support.",
    "score": 98,
    "status": "active",
    "specs": [
      "Pellicle 8Z Breathable Suspension Mesh",
      "PostureFit SL Dual Sacral & Lumbar Stabilizer",
      "Harmonic 2 Tilt with Forward Angle Adjustment",
      "Fully Adjustable 3D Cushioned Armrests",
      "12-Year Herman Miller 24/7 Warranty"
    ]
  },
  {
    "name": "Uplift V2 Commercial Standing Desk",
    "slug": "uplift-v2-commercial-standing-desk",
    "merchant": "Uplift Desk",
    "source_url": "https://www.upliftdesk.com/uplift-v2-standing-desk-v2-or-v2-commercial/",
    "affiliate_url": "https://www.upliftdesk.com/uplift-v2-standing-desk-v2-or-v2-commercial/",
    "image_url": "/images/products/uplift-v2-standing-desk.svg",
    "price": "$699.00",
    "old_price": "$799.00",
    "is_deal": true,
    "discount_percent": 13,
    "deal_badge": "13% OFF",
    "rating": 4.8,
    "review_count": 3890,
    "category": "Desk Setup",
    "description": "Heavy-duty three-stage commercial standing desk frame with lower crossbar reinforcement for rock-solid stability holding dual 32-inch monitor setups.",
    "score": 95,
    "status": "active",
    "specs": [
      "Dual German Motors with 355-lb Capacity",
      "Height Range: 22.6\" to 48.7\" (ANSI/BIFMA Certified)",
      "Digital Memory Handset with 4 Presets",
      "Crossbar Frame Stability Guarantee",
      "One-Inch Thick Solid Core Desktop"
    ]
  },
  {
    "name": "Sony WH-1000XM5 Wireless Headphones",
    "slug": "sony-wh-1000xm5-wireless-headphones",
    "merchant": "Sony",
    "source_url": "https://electronics.sony.com/audio/headphones/headband-headphones/p/wh1000xm5-b",
    "affiliate_url": "https://electronics.sony.com/audio/headphones/headband-headphones/p/wh1000xm5-b",
    "image_url": "/images/products/sony-wh-1000xm5.svg",
    "price": "$398.00",
    "old_price": "$398.00",
    "is_deal": false,
    "discount_percent": 0,
    "deal_badge": null,
    "rating": 4.7,
    "review_count": 12400,
    "category": "Headphones",
    "description": "Class-leading active noise cancellation powered by two processors and 8 microphones. Blocks office distractions and mechanical keyboard chatter during deep work.",
    "score": 95,
    "status": "active",
    "specs": [
      "Integrated Processor V1 & HD Noise Cancelling QN1",
      "8 Microphones with AI Noise Reduction",
      "30 Hours Battery (3-minute charge = 3 hours playback)",
      "Multipoint Bluetooth 5.2 Device Pairing",
      "Lightweight Soft-Fit Synthetic Leather Design"
    ]
  },
  {
    "name": "Bose QuietComfort Ultra Earbuds",
    "slug": "bose-quietcomfort-ultra-earbuds",
    "merchant": "Bose",
    "source_url": "https://www.bose.com/p/earbuds/bose-quietcomfort-ultra-earbuds/QCUE-HEADPHONEIN.html",
    "affiliate_url": "https://www.bose.com/p/earbuds/bose-quietcomfort-ultra-earbuds/QCUE-HEADPHONEIN.html",
    "image_url": "/images/products/bose-qc-ultra.svg",
    "price": "$249.00",
    "old_price": "$299.00",
    "is_deal": true,
    "discount_percent": 17,
    "deal_badge": "17% OFF",
    "rating": 4.6,
    "review_count": 4100,
    "category": "Headphones",
    "description": "In-ear acoustic silence with Bose CustomTune audio calibration. Offers spatial immersive audio in an ultra-compact pocketable form factor.",
    "score": 91,
    "status": "active",
    "specs": [
      "CustomTune Personalized Ear Canal Acoustics",
      "Bose Immersive Spatial Audio Engine",
      "9 Fit Combinations with Umbrella Tips & Bands",
      "Up to 6 Hours Battery (24 Hours with Case)",
      "IPX4 Sweat & Weather Resistance"
    ]
  },
  {
    "name": "Roost V3 Ultra-Portable Laptop Stand",
    "slug": "roost-v3-ultra-portable-laptop-stand",
    "merchant": "Roost",
    "source_url": "https://www.therooststand.com/",
    "affiliate_url": "https://www.therooststand.com/",
    "image_url": "/images/products/roost-v3-laptop-stand.svg",
    "price": "$89.95",
    "old_price": "$89.95",
    "is_deal": false,
    "discount_percent": 0,
    "deal_badge": null,
    "rating": 4.8,
    "review_count": 2850,
    "category": "Desk Setup",
    "description": "The gold standard for traveling developers and coffee shop workers. Weighs just 5.8 oz and collapses in one swift motion into a compact baton while lifting screens up to 14 inches.",
    "score": 92,
    "status": "active",
    "specs": [
      "Ultra-Lightweight 5.8 oz Carbon & Delrin Build",
      "7 Quick-Adjust Ergonomic Height Settings",
      "Patented Pivoting Grips Fit Laptops of Any Thickness",
      "Collapses into 1.3\" x 1.3\" x 13\" Compact Baton",
      "Engineered in USA, Includes Ripstop Sleeve"
    ]
  },
  {
    "name": "Twelve South Curve Desktop Stand for MacBooks",
    "slug": "twelve-south-curve-desktop-stand",
    "merchant": "Twelve South",
    "source_url": "https://www.twelvesouth.com/products/curve-for-macbook",
    "affiliate_url": "https://www.twelvesouth.com/products/curve-for-macbook",
    "image_url": "/images/products/twelve-south-curve.svg",
    "price": "$59.99",
    "old_price": "$59.99",
    "is_deal": false,
    "discount_percent": 0,
    "deal_badge": null,
    "rating": 4.6,
    "review_count": 1980,
    "category": "Desk Setup",
    "description": "Minimalist sculpted aluminum stand that elevates laptops 6.5 inches to match external monitors. Provides unhindered 360-degree cooling airflow.",
    "score": 89,
    "status": "active",
    "specs": [
      "Seamless Matte Aluminum Sculpted Architecture",
      "Elevates Screen 6.5 Inches for Eye-Level Ergonomics",
      "Exposes 70% of Base for Maximum Heat Dissipation",
      "Anti-Slip Silicone Arm Grips",
      "Color-Matched Matte Black & White Finishes"
    ]
  },
  {
    "name": "BenQ ScreenBar Halo LED Monitor Light Bar",
    "slug": "benq-screenbar-halo-monitor-light",
    "merchant": "BenQ",
    "source_url": "https://www.benq.com/en-us/lighting/monitor-light/screenbar-halo.html",
    "affiliate_url": "https://www.benq.com/en-us/lighting/monitor-light/screenbar-halo.html",
    "image_url": "/images/products/benq-screenbar-halo.svg",
    "price": "$179.00",
    "old_price": "$179.00",
    "is_deal": false,
    "discount_percent": 0,
    "deal_badge": null,
    "rating": 4.7,
    "review_count": 1890,
    "category": "Productivity",
    "description": "Patented asymmetric optical monitor light with zero screen reflection. Features an ambient rear bias light and a desktop wireless rotary controller.",
    "score": 93,
    "status": "active",
    "specs": [
      "Patented Asymmetric Optical Design (Zero Glare)",
      "Dual Front & Rear Ambient Bias Illumination",
      "Precision Wireless Rotary Dial Controller",
      "Built-In Ambient Light Sensor with Auto-Dimming",
      "Compatible with Curved Monitors (1000R to 1800R)"
    ]
  },
  {
    "name": "CalDigit TS4 Thunderbolt 4 Dock (18-in-1)",
    "slug": "caldigit-ts4-thunderbolt-4-dock",
    "merchant": "CalDigit",
    "source_url": "https://www.caldigit.com/thunderbolt-station-4/",
    "affiliate_url": "https://www.caldigit.com/thunderbolt-station-4/",
    "image_url": "/images/products/caldigit-ts4-dock.svg",
    "price": "$399.99",
    "old_price": "$399.99",
    "is_deal": false,
    "discount_percent": 0,
    "deal_badge": null,
    "rating": 4.8,
    "review_count": 2200,
    "category": "Productivity",
    "description": "The ultimate single-cable workstation dock. Offers 18 ports, 98W laptop charging, 2.5GbE networking, and dual 6K display support with an aluminum heatsink body.",
    "score": 96,
    "status": "active",
    "specs": [
      "18 Connectivity Ports (3x TB4, 5x USB-A, 3x USB-C)",
      "98W Dynamic Host Laptop Power Delivery",
      "Dual 6K 60Hz or Single 8K Display Output",
      "2.5 Gigabit High-Speed Ethernet",
      "Front UHS-II SD 4.0 & MicroSD Card Slots"
    ]
  },
  {
    "name": "Orbitkey Desk Mat with Magnetic Cable Holder",
    "slug": "orbitkey-desk-mat-magnetic-cable-bar",
    "merchant": "Orbitkey",
    "source_url": "https://www.orbitkey.com/products/orbitkey-desk-mat",
    "affiliate_url": "https://www.orbitkey.com/products/orbitkey-desk-mat",
    "image_url": "/images/products/orbitkey-desk-mat.svg",
    "price": "$68.00",
    "old_price": "$68.00",
    "is_deal": false,
    "discount_percent": 0,
    "deal_badge": null,
    "rating": 4.6,
    "review_count": 1450,
    "category": "Desk Setup",
    "description": "Smart organization desk mat featuring an integrated document hideaway toolbar and a magnetic sliding cable anchor to prevent cables from dropping behind desks.",
    "score": 88,
    "status": "active",
    "specs": [
      "Premium Vegan Polyurethane Leather & Recycled Felt",
      "Hidden Toolbar Layer for Storing Paper Notes",
      "Magnetic Cable Anchor Slides Smoothly Across Toolbar",
      "Water-Resistant Spill-Proof Easy-Clean Surface",
      "Dimensions: 35.3\" x 16.6\" (Large Size)"
    ]
  },
  {
    "name": "Anker 737 Power Bank (PowerCore 24K, 140W)",
    "slug": "anker-737-power-bank-powercore-24k",
    "merchant": "Anker",
    "source_url": "https://www.anker.com/products/a1289",
    "affiliate_url": "https://www.anker.com/products/a1289",
    "image_url": "/images/products/anker-737-power-bank.svg",
    "price": "$109.99",
    "old_price": "$149.99",
    "is_deal": true,
    "discount_percent": 27,
    "deal_badge": "27% OFF",
    "rating": 4.7,
    "review_count": 6800,
    "category": "Productivity",
    "description": "Massive 24,000mAh portable charger with 140W two-way fast charging and a full-color smart digital display showing output wattage and battery cycle health.",
    "score": 94,
    "status": "active",
    "specs": [
      "24,000mAh Airline-Safe High-Capacity Cell",
      "140W Two-Way USB-C Power Delivery 3.1",
      "Color Smart Digital Display with Real-Time Stats",
      "Simultaneous 3-Device Charging (2x USB-C, 1x USB-A)",
      "ActiveShield 2.0 Temperature Monitoring (3M checks/day)"
    ]
  }
];
