-- Cuelinks V3 Affiliate Integration Schema
-- Tables for tracking affiliate campaigns and link conversions

CREATE TABLE IF NOT EXISTS public.affiliate_campaigns (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  provider TEXT NOT NULL DEFAULT 'cuelinks',
  external_campaign_id INTEGER NOT NULL UNIQUE,
  merchant_name TEXT NOT NULL,
  campaign_name TEXT NOT NULL,
  domain TEXT,
  country TEXT,
  category TEXT,
  access_status TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'active',
  payout TEXT,
  payout_type TEXT,
  epc TEXT,
  deep_link_supported BOOLEAN DEFAULT true,
  allowed_media JSONB DEFAULT '[]'::jsonb,
  disallowed_media JSONB DEFAULT '[]'::jsonb,
  allowed_platforms JSONB DEFAULT '[]'::jsonb,
  disallowed_platforms JSONB DEFAULT '[]'::jsonb,
  affiliated_test_result BOOLEAN,
  last_checked_at TIMESTAMPTZ DEFAULT NOW(),
  raw_metadata JSONB DEFAULT '{}'::jsonb
);

CREATE TABLE IF NOT EXISTS public.affiliate_links (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  provider TEXT NOT NULL DEFAULT 'cuelinks',
  campaign_id INTEGER,
  merchant TEXT,
  original_url TEXT NOT NULL,
  tracking_url TEXT NOT NULL,
  short_url TEXT,
  affiliated BOOLEAN NOT NULL DEFAULT false,
  channel_id TEXT,
  subid TEXT,
  subid2 TEXT,
  subid3 TEXT,
  subid4 TEXT,
  subid5 TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  last_verified_at TIMESTAMPTZ DEFAULT NOW()
);

-- Unique index to prevent duplicate affiliate links
CREATE UNIQUE INDEX IF NOT EXISTS idx_affiliate_links_dedup 
  ON public.affiliate_links (provider, campaign_id, original_url);

-- Product table extension for affiliate attribution
ALTER TABLE public.products
  ADD COLUMN IF NOT EXISTS merchant_campaign_id INTEGER,
  ADD COLUMN IF NOT EXISTS merchant_url TEXT,
  ADD COLUMN IF NOT EXISTS affiliate_short_url TEXT,
  ADD COLUMN IF NOT EXISTS affiliate_provider TEXT DEFAULT 'cuelinks',
  ADD COLUMN IF NOT EXISTS currency TEXT DEFAULT 'INR',
  ADD COLUMN IF NOT EXISTS availability TEXT DEFAULT 'in_stock',
  ADD COLUMN IF NOT EXISTS last_verified_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS published BOOLEAN DEFAULT true;

CREATE TABLE IF NOT EXISTS public.affiliate_access_requests (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  request_id BIGINT,
  campaign_id INTEGER NOT NULL,
  channel_id BIGINT,
  promotion_details TEXT NOT NULL,
  request_status TEXT NOT NULL DEFAULT 'pending',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable RLS and add access policies
ALTER TABLE public.affiliate_campaigns ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.affiliate_links ENABLE ROW LEVEL SECURITY;

DO $$ 
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies WHERE tablename = 'affiliate_campaigns' AND policyname = 'Allow select for all'
  ) THEN
    CREATE POLICY "Allow select for all" ON public.affiliate_campaigns FOR SELECT USING (true);
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_policies WHERE tablename = 'affiliate_campaigns' AND policyname = 'Allow service_role full access'
  ) THEN
    CREATE POLICY "Allow service_role full access" ON public.affiliate_campaigns FOR ALL USING (true) WITH CHECK (true);
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_policies WHERE tablename = 'affiliate_links' AND policyname = 'Allow select for all'
  ) THEN
    CREATE POLICY "Allow select for all" ON public.affiliate_links FOR SELECT USING (true);
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_policies WHERE tablename = 'affiliate_links' AND policyname = 'Allow service_role full access'
  ) THEN
    CREATE POLICY "Allow service_role full access" ON public.affiliate_links FOR ALL USING (true) WITH CHECK (true);
  END IF;
END $$;
